# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

# Name of website
title: 邦盈移加易

# Short description of your site
description: 移民咨询 移民服务 雇主担保 创业移民 自雇移民 技术移民 邦盈 移加易 在线学习

# GitHub Actions
repository: "VincentTam/beautiful-jekyll"

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this mean, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# Your name to show in the footer
author: 移民小舟

baidu-site-verification: "code-nTSuT9Ql1Q"
# --- List of links in the navigation bar --- #

navbar-links:
  关于邦盈: "aboutme"
  移民项目:
    - BC雇主担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485628&idx=3&sn=7927bfdc55d469b47a103b100a3b0905&chksm=c35ad2bff42d5ba98e72196bff0425441ca340ad4ea9eefc3cd3227f462541d38f41548bf3cb&scene=21#wechat_redirect"
    - NB省雇主担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485533&idx=3&sn=3a901fa2be2b2c0bb63e524db91ddf7e&chksm=c35ad25ef42d5b4886af6d7518422891a9f92c77464bdb4bc6750574ca2ffbb2dc0c454c7890&scene=21#wechat_redirect"
    - 安省雇主担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485516&idx=1&sn=2117efe672963984ba01e14c60538912&chksm=c35ad24ff42d5b5962b189af352ddee1e9cee855460e7ef178e48040ab0259488ad48238f87e&scene=21#wechat_redirect"
    - 萨省企业家移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485516&idx=4&sn=51b4c09dea03bd7949a141bb3a385316&chksm=c35ad24ff42d5b5918f6052910f3ef838ff80c18cf9f56ccfa7a251521b6a5f9cd1542863952&scene=21#wechat_redirect"
    - 萨省雇主担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485628&idx=4&sn=de123687aaaeaadc36ce474cbb7f61e0&chksm=c35ad2bff42d5ba952ceb8edbd85e70c8e875ba592b34c69cdf8438d11ce946d0281c580cbe0&scene=21#wechat_redirect"
    - 魁省技术移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485526&idx=3&sn=44070366ceefb1974c9736a0f16b2a26&chksm=c35ad255f42d5b43833e5706a733cd8fdb7db02121bf8bc718f08d8558ef9f2fbf82ca9043cc&scene=21#wechat_redirect"
    - 联邦创业移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485526&idx=2&sn=1d0a72a3cf3239d75aec1585aac9b041&chksm=c35ad255f42d5b43d7f9b422c98998c9cf2580b3116cb000753046684cfb383c4c5689ff1c65&scene=21#wechat_redirect"
    - 联邦自雇移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485526&idx=1&sn=339a4e7dca2303749d3396168a8c3126&chksm=c35ad255f42d5b430350db1c214e9018be35cad868e3dc5555148775ea799557d8860c72afd9&scene=21#wechat_redirect"
    - 留学转移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485516&idx=2&sn=bf7ba7e79564f0b06ed9cfd3aa0cf2e1&chksm=c35ad24ff42d5b5907a25f41decc022c3781fb0769615d8cc11eab0b7adcf1350798cf8bd933&scene=21#wechat_redirect"
    - 大西洋四省移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485526&idx=4&sn=2ee208fe22ad136405872e4917fe3b71&chksm=c35ad255f42d5b4315f20938a4cc3bf7fd90b4f0b854fd74722cf6587f6af1cf1b7337804097&scene=21#wechat_redirect"
    - 爱德华王子岛投资: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485648&idx=2&sn=9cc5777f0f7433aa79a2d34037932c52&chksm=c35ad2d3f42d5bc591890c6083242b3800ba2e68c18be1ca7d7a4a48d6254fb627956cb401d1&scene=21#wechat_redirect"
  成功案例: "chenggonganli"
  服务内容: "fuwuneirong"
  自雇课堂: "https://apprxycjw0d7727.h5.xiaoeknow.com/p/decorate/homepage"
  小工具: 
    - EE CRS: "EE_CRS.html"
    - 联邦技术移民打分: "EE_SCORE.html"
    - BCPNP技术打分: "BCPNP.html"
    - 安省雇主担保打分: "ONIP.html"
 
  #Author's home: "https://deanattali.com"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/邦盈.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: /assets/img/邦盈.png


# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "joy.zhou@easyimmi.cn"
  xiaohongshu: easyimmi
  wechat: easyimmi
  tiktok: easyimmi
#  github: daattali
#  douyin: yiminxiaozhou
#  patreon: yiminxiaozhou
#  youtube: yiminxiaozhou
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
#  google-scholar: your google scholar

# If you want to show a link to an RSS in the footer, add the site description here.
# If you don't want to show an RSS link, remove the following line.
# rss-description: This website is a virtual proof that I'm awesome

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  #xiaohongshu: true
  #tiktok: true
  #douyin: true
  #vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "easyimmi.cn"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# The keywords to associate with your website, for SEO purposes
keywords: "移民咨询,咨询,移民中介,中介,中介服务,移民服务,移民小舟,移民文案,文案,文案服务,雇主资源,商业计划书,考察,BP,商业考察,移民周麻麻,easyimmi.cn,easyimmi,枫叶卡,绿卡,PR,永居,身份,工签,移民签,学签,邦盈移加易,邦盈,移加易,青岛邦盈,移民,加拿大移民,加拿大,雇主担保移民,投资移民,技术移民,澳洲移民,创业移民,省提名,自雇移民,留学转移民,旅转学,创业移民,海外移民,邦盈海外,环球海外,飞出国,材料,料简,简化,中国公民,民办,办理,签证,更便,便捷"

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# --- Web Analytics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using Google Analytics
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, uncomment the following section. You may leave the reCaptcha
# section commented if you aren't using reCaptcha for spam protection. 
# Using Staticman requires advanced knowledge, please consult 
# https://github.com/eduardoboucas/staticman/ and https://staticman.net/ for further 
# instructions. For any support with staticman please direct questions to staticman and 
# not to BeautifulJekyll.
staticman:
  repository : vincenttam/beautiful-jekyll # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : gh-pages # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : https://secretman3.herokuapp.com/v3/entry/github/ # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well) 
#    siteKey  : # You need to apply for a site key on Google
#    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/ShangHai"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

#remote_theme: daattali/beautiful-jekyll@5.0.0

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
